version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - ./data:/app/data
      - ./images:/app/app/static/plants

    environment:
      - JWT_SECRET=iAWQa9RNJ2nhQgMfvLVls7eJI2oq8TR2
      - ADMIN_USER=admin
      - ADMIN_PASS=adminpass