version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - ./data:/app/data:ro
      - ./images:/app/app/static/plants
    environment:
      - JWT_SECRET=change-me-please
      - ADMIN_USER=admin
      - ADMIN_PASS=admin123