# render.yaml
# This is a blueprint for deploying your application on Render.
# It's based on the provided docker-compose.yml file.

services:
  # Defines the web service for your application.
  - type: web
    name: korean-medicine-app # A descriptive name for your service
    env: docker # Specifies that the service is built from a Dockerfile
    
    # --- Build & Start ---
    # Render will automatically detect and use the Dockerfile in your root directory.
    # The internal port your app listens on should be exposed in your Dockerfile (e.g., EXPOSE 8000).
    # Render sets the PORT environment variable, which your app should use if possible.
    # If your app is hardcoded to port 8000, that's fine too.
    
    # --- Plan ---
    # Choose a plan that fits your needs. 'starter' is a good default.
    # Free plans have limitations on persistent storage and may spin down.
    plan: starter 

    # --- Environment Variables ---
    # These are equivalent to the 'environment' section in docker-compose.
    # For sensitive values like JWT_SECRET and ADMIN_PASS, it's highly recommended 
    # to create "Secret Files" in the Render dashboard and link them here for better security.
    envVars:
      - key: JWT_SECRET
        value: iAWQa9RNJ2nhQgMfvLVls7eJI2oq8TR2
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: adminpassword

    # --- Persistent Disks ---
    # This section replaces the 'volumes' from your docker-compose file.
    # It creates persistent storage that survives deploys and restarts.
    disks:
      - name: data
        mountPath: /app/data
        sizeGB: 1 # You can adjust the size as needed
      - name: images
        mountPath: /app/app/static/plants
        sizeGB: 1 # You can adjust the size as needed
